### ISSUE TITLE
Add Unibeautify Configuration file loader support

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/vscode#10]
See https://unibeautify.com/docs/config-file.html 

TODO:
- [x] Add [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)
- [x] Configure `cosmiconfig`:

```typescript
const configModuleName = 'unibeautify';
const configOptions = {
  rcExtensions: true
};
const configExplorer = cosmiconfig(configModuleName, configOptions);
```

- [x] Load configuration with `configExplorer`:

```typescript
const defaultConfig = {};
return this.configExplorer
      .load(this.repoPath)
      .then(result => (result ? result.config : defaultConfig));
```

- [x] Change `beautifierOptions`:

https://github.com/Unibeautify/vscode/blob/master/src/EditProvider.ts#L40-L50

```typescript
const beautifyOptions: LanguageOptionValues = {}; // REPLACE WITH CONFIG FROM COSMICONFIG
const beautifyData: BeautifyData = {
      languageName,
      fileExtension,
      filePath,
      projectPath,
      options: beautifyOptions,
      text,
};
```

**Comment by mmn6d6d6e** [comment]
Where should I put config file?
Already tried to put it on project root, but ignored.

**.unibeautifyrc.json**
```
{
    "JavaScript": {
        "end_with_comma": true,
        "end_with_semicolon": false
    }
}
```

**Comment by Glavin001** [comment]
The configuration file (`.unibeautify.json`) support is currently not implemented for VSCode. This is the next feature which should be added.


We are looking for contributors! If you are up for it, please make a Pull Request! Thank you in advance!

**Comment by Glavin001** [comment]
I added detailed TODO steps to the Issue above. This should be enough for someone to contribute a PR adding the configuration support. Thank you for your interest in Unibeautify!

**Comment by szeck87** [comment]
I added that code and added a `.unibeautifyrc` file in the testProject directory.  I then ran the extension in debug mode, when the `.load()` function was called it couldn't find the file `/.unibeautifyrc`.  It automatically starts at process.cwd() and starts going up from there.  So it should have found it.  Maybe I'll give Atom Beautify a go at this feature first.

**Comment by Glavin001** [comment]
I'm going to try and take this on. Please let me know if you've already started 👍.

**Comment by Glavin001** [comment]
Pull Request in need of reviewing: https://github.com/Unibeautify/vscode/pull/16 

After #8 , we should add some more test. I have been working on it, however I think I would use `jest.mock` and don't want to invest too much time into the tests right now since #8 is in progress.

**Comment by Glavin001** [comment]
WIP code snippet for tests: Not particularly useful yet.

```typescript
/* global suite, test */

//
// Note: This example test is leveraging the Mocha test framework.
// Please refer to their documentation on https://mochajs.org/ for help.
//

// The module 'assert' provides assertion methods from node
const assert = require("assert");

// You can import and use all API from the 'vscode' module
// as well as import your extension to test it
import * as vscode from "vscode";
import * as extension from "../src";
import { EditProvider } from "../src/EditProvider";
import { Edit } from "../src/diffUtils";
import { LanguageOptionValues } from "unibeautify";
import * as path from "path";

// Defines a Mocha test suite to group tests of similar kind together
suite("EditProvider", function() {

});

function testFormatFile(fileName: string) {
  // Defines a Mocha unit test
  test(`should format file ${fileName}`, function() {
    
  });
}

export function format(file: string, base: vscode.Uri = vscode.workspace.workspaceFolders![0].uri) {
  const absPath = path.join(
      base.fsPath,
      file
  );
  return vscode.workspace.openTextDocument(absPath).then(doc => {
      const text = doc.getText();
      return vscode.window.showTextDocument(doc).then(
          () => {
              console.time(file);
              return vscode.commands
                  .executeCommand('editor.action.formatDocument')
                  .then(() => {
                      console.timeEnd(file);
                      return { result: doc.getText(), source: text };
                  });
          },
          e => console.error(e)
      );
  });
}


function createEditProviderWithConfig(
  config: LanguageOptionValues,
): EditProvider {
  class CustomEditProvider extends EditProvider {
    beautifyOptions(filePath: string): Promise<LanguageOptionValues> {
      return Promise.resolve(config);
    }
  }
  return new CustomEditProvider();
}
```

**Comment by Glavin001** [comment]
Published to v0.3.0!

**Comment by Glavin001** [comment]
@mmn6d6d6e : Please update and give it another try! Let me know if you have any more troubles. Thanks! 😃

**Comment by mmn6d6d6e** [comment]
Thank you, @Glavin001. Tested. Works beautifully.
