### ISSUE TITLE
Unable to publish "peer dep missing"

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/vscode#11]
Related to: https://github.com/npm/npm/issues/19877 , https://github.com/npm/npm/issues/15708 , https://github.com/yarnpkg/yarn/issues/4850 , https://stackoverflow.com/a/48318878/2578205 , https://github.com/yarnpkg/yarn/issues/4743 , https://github.com/yarnpkg/yarn/pull/5088

```
❯ vsce publish
Executing prepublish script 'npm run vscode:prepublish'...

> unibeautify-vscode@0.1.0 vscode:prepublish /Users/glavin/Development/unibeautify/vscode
> npm run build


> unibeautify-vscode@0.1.0 build /Users/glavin/Development/unibeautify/vscode
> tsc

Error: Command failed: npm list --production --parseable --depth=99999
npm ERR! peer dep missing: unibeautify@^0.9.2, required by @unibeautify/beautifier-eslint@0.4.0
npm ERR! peer dep missing: unibeautify@^0.8.0, required by @unibeautify/beautifier-js-beautify@0.3.1
npm ERR! peer dep missing: unibeautify@^0.8.0, required by @unibeautify/beautifier-prettier@0.7.3
npm ERR! peer dep missing: unibeautify@^0.9.1, required by @unibeautify/beautifier-prettydiff@0.5.2
```

and

```
❯ npm install

> unibeautify-vscode@0.1.0 postinstall /Users/glavin/Development/unibeautify/vscode
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.6.0
Found minimal version that qualifies engine range: 1.6.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/e52fb0bc87e6f5c8f144e172639891d8d8c9aa55/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

npm WARN @unibeautify/beautifier-eslint@0.4.0 requires a peer of unibeautify@^0.9.2 but none is installed. You must install peer dependencies yourself.
npm WARN @unibeautify/beautifier-js-beautify@0.3.1 requires a peer of unibeautify@^0.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @unibeautify/beautifier-prettier@0.7.3 requires a peer of unibeautify@^0.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @unibeautify/beautifier-prettydiff@0.5.2 requires a peer of unibeautify@^0.9.1 but none is installed. You must install peer dependencies yourself.

up to date in 6.171s
```

**Comment by Glavin001** [comment]
To reproduce without actually publishing run:

```bash
npm list --production --parseable --depth=99999
```

Help wanted! I am stuck here.

**Comment by tdillon** [comment]
Can you update the unibeautify dependency/peerDependency version in `beautifier-eslint`, `beautifier-js-beautify`, `beautifier-prettier`, and `beautifier-prettydiff`?  I updated them to `^0.10.1` and `npm list --production --parseable --depth=99999` did not error.  Since the version of `unibeautify` you are depending on in `unibeautify/vscode` is `0.10.1` the peerDependencies in your `beautifier-*` projects must be at least `^0.10.0`.  See https://docs.npmjs.com/misc/semver

**Comment by szeck87** [comment]
So until version 1.0.0 rolls around, we should treat the minor version as one that could have breaking changes.  From https://docs.npmjs.com/misc/semver:

> Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases, which is a common practice. However, it presumes that there will not be breaking changes between 0.2.4 and 0.2.5

So we want to use >= 0.9.x?

**Comment by Glavin001** [comment]
Fixed it!!! 🎉

**Comment by Glavin001** [comment]
Will publish this weekend 👍.

Until then, Pull Requests are very welcome!!! 🎉

**Comment by Glavin001** [comment]
Published! https://marketplace.visualstudio.com/items?itemName=Glavin001.unibeautify-vscode
