### ISSUE TITLE
Disabling a language not longer working

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/vscode#113]
I want to have SCSS formatting disabled because I have another plugin that handles this for me. I have this Unibeautify configuration: https://hastebin.com/ukimobozog.json

I tried to `"SCSS": false,` and 
```
"SCSS": {
    "enabled": false
  },
```
and I removed it from my config. Nothing worked. I would expect at least try one and three should work.

**Comment by szeck87** [comment]
Looks like `scss` is in the `vscodeLanguages` for sass.  You'll have to disable them both.  I'll create an issue in Unibeautify, I see a few problems in that file.

**Comment by muuvmuuv** [comment]
Thanks @szeck87!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
