### ISSUE TITLE
Is there a way to have a global config file or does it need to be per project?

### ISSUE THREAD

**Issue by steveparrynz** [Unibeautify/vscode#121]
If there is great, where do you need to store it.

If not, I think this would be a great feature. You could have a global config and then also have per project that would either get used instead of or in conjunction with where values just over rule what is in the global.

**Comment by szeck87** [comment]
There is a `Default Config` field in VSCode's Settings for Unibeautify.  If there is no configuration file found in your workspace, it will use that as a fallback.

![screen shot 2018-08-29 at 5 54 09 pm](https://user-images.githubusercontent.com/8315038/44820082-fce30700-abb4-11e8-9ef5-7d0b5b7f7e86.png)

**Comment by steveparrynz** [comment]
Ah perfect, sorry didn't see that area. It might be worth updating the readme area to mention that this is available. As it stands it seems like you need to have it per project.

**Comment by Glavin001** [comment]
Good idea, @steveparrynz . Pull Requests are very welcome for edits to https://github.com/Unibeautify/vscode#question-faq to include a note about this feature! Thanks in advance!

**Comment by Glavin001** [comment]
Related to https://github.com/Unibeautify/vscode/issues/55 and https://github.com/Unibeautify/vscode/pull/57

**Comment by muuvmuuv** [comment]
I'll add this under the [config](https://github.com/Unibeautify/vscode#wrench-configure) section while I'm working on the new FAQ entry. @Glavin001 @szeck87
