### ISSUE TITLE
prefer beautifier config not working

### ISSUE THREAD

**Issue by chipco** [Unibeautify/vscode#160]
I can't seem to get PHP-CS-Fixer or CSScomb to work with unibeautify in vscode windows 10. When I try to format a php or css file nothing happens.

My config file is:
```
{
	"PHP": {
		"beautifiers": [
			"PHP-CS-Fixer"
		],
		"PHP-CS-Fixer": {
			"prefer_beautifier_config": true
		}
	},
	"CSS": {
		"beautifiers": [
			"CSScomb"
		],
		"CSScomb": {
			"prefer_beautifier_config": true
		},
		"indent_style": "tab",
		"indent_size": "1",
		"end_with_newline": true
	},
	"JavaScript": {
		"beautifiers": [
			"JS-Beautify",
			"ESLint"
		],
		"indent_style": "tab",
		"indent_size": "1",
		"end_with_newline": true,
		"max_preserve_newlines": "2",
		"preserve_newlines": true,
		"jslint_happy": true,
		"quotes": "single",
		"multiline_ternary": "never",
		"brace_style": "collapse-preserve-inline",
		"object_curly_spacing": false
	}
}
```

I did try with the formatters available in PATH. Also tried to provide the absolute path in the `path` property.

**Comment by stevenzeck** [comment]
Hi @chipco. Can you update the code you posted with the path properties?

Are there messages in the output in terminal view? Or any errors in developer console (Help > Toggle Developer Tools)

**Comment by chipco** [comment]
There's no message in the output.

I managed to get php-cs-fixer working, it looks like I need to add .bat extension. However It's not picking up my config file `.php-cs`.

```
	"PHP": {
		"beautifiers": [
			"PHP-CS-Fixer"
		],
		"PHP-CS-Fixer": {
			"prefer_beautifier_config": true,
			"PHP-CS-Fixer": {
				"path": "C:\\Users\\Chip\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer.bat"
			}
		}
	},
```

CSScomb still doesn't do anything.
```
$ where csscomb
C:\Users\Chip\AppData\Roaming\npm\csscomb
C:\Users\Chip\AppData\Roaming\npm\csscomb.cmd

	"CSS": {
		"beautifiers": [
			"CSScomb"
		],
		"CSScomb": {
			"prefer_beautifier_config": true,
			"CSScomb": {
				"path": "C:\\Users\\Chip\\AppData\\Roaming\\npm\\csscomb.cmd"
			}
		}
	},
```

**Comment by stevenzeck** [comment]
Ok, I'll come back to CSScomb. Where is your php_cs file located in relation to your project and the unibeautify json config file?

**Comment by chipco** [comment]
The folder structure is something like:

```
D:\web\
	.csscomb.json
	.php-cs
	.unibeautifyrc.json
	project1\
	project2\
```

In my current vscode workspace I have opened the folder D:\web\project1

**Comment by stevenzeck** [comment]
I need to test it with a structure like this when I get home. It will start looking for the php_cs in the same directory of the file you are trying to beautify, and will keep going up a directory looking for it until it reaches the project root. The root in this case might be project1, do it doesn't look under /web.

**Comment by chipco** [comment]
Placing the file `.php_cs` in project1 folder worked.

Is there any config option for a global file outside the project folder?

**Comment by stevenzeck** [comment]
I can't remember if we did that or not, @Glavin001 so you know?

**Comment by Glavin001** [comment]
> Is there any config option for a global file outside the project folder?

I think this is the same question as: https://github.com/Unibeautify/vscode/issues/121#issuecomment-417133868

Answer: https://github.com/Unibeautify/vscode#pushpin-default-configuration

Let me know if that doesn't work for you 😃

**Comment by stevenzeck** [comment]
That is for the unibeautify config file. What about the beautifier config file such as `.php_cs`? Can that be put in the unibeautify config file?

**Comment by Glavin001** [comment]
> What about the beautifier config file such as `.php_cs`?

Oh, the path for `.php_cs` when `prefer_beautifier_config` is enabled. 🤔 

I think the current answer would be **No**: https://github.com/Unibeautify/beautifier-php-cs-fixer/blob/master/src/index.ts#L77-L83

The beautifier looks for the `.php_cs` file only up to the VSCode project root.

**Comment by stevenzeck** [comment]
That's how beautifier-php-cs-fixer attempts to find the file. I didn't know if unibeautify core did anything in the background and sent to the beautify method for the beautifier.

**Comment by Glavin001** [comment]
@stevenzeck Nope, doesn't look like it: https://github.com/Unibeautify/unibeautify/blob/master/src/beautifier.ts#L397-L411

**Comment by stevenzeck** [comment]
@chipco unfortunately for now you'll need to put your `.php.cs` file in the same directory as your workspace or lower.

Sorry I missed your comment earlier that CSSComb is working now.  But you shouldn't have to put the path to it unless you prefer to run your own installation, it is included in the Unibeautify VSCode plugin.  

What was the other VSCode extension that was causing a conflict?

**Comment by chipco** [comment]
> What was the other VSCode extension that was causing a conflict?

https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-csscomb

**Comment by chipco** [comment]
Should I close this? The original post was about a config issue on my side.

**Comment by stevenzeck** [comment]
I'll close it. Feel free to follow https://github.com/Unibeautify/unibeautify/issues/221 for being able to specify the path to your config.

**Comment by scsshomugenxv** [comment]
Since php-cs-fixer and phpcbf can have default rules set, would it be possible for unibeautify to run them without specifying a config file?

**Comment by stevenzeck** [comment]
@scsshomugenxv you don't have to have any config file for it to run, it will just use whatever defaults is built into it.
