### ISSUE TITLE
Not formatting php

### ISSUE THREAD

**Issue by scsshomugenxv** [Unibeautify/vscode#169]
I can't seem to get Unibeautify to format php using php-cs-fixer or phpcbf. with or without a config file the console gives me the error:   The "--using-cache" option does not exist.

**Comment by stevenzeck** [comment]
@scsshomugenxv can you share your Unibeautify configuration file?

**Comment by scsshomugenxv** [comment]
{
  "PHP": {
    "beautifiers": ["PHP-CS-Fixer"],
    "PHP-CS-Fixer": {
      "prefer_beautifier_config": true,
      "PHP-CS-Fixer": {
        "path": "C:\\Users\\chris\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer.bat"
      }
    }
  }
}

**Comment by scsshomugenxv** [comment]
{
  "PHP": {
    "beautifiers": ["PHP-CS-Fixer"],
    "PHP-CS-Fixer": {
      "prefer_beautifier_config": true,
      "PHP-CS-Fixer": {
        "path": "C:\\Users\\chris\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer.bat"
      }
    }
  }
}

**Comment by scsshomugenxv** [comment]
`{
  "PHP": {
    "beautifiers": ["PHP-CS-Fixer"],
    "PHP-CS-Fixer": {
      "prefer_beautifier_config": true,
      "PHP-CS-Fixer": {
        "path": "C:\\Users\\chris\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer.bat"
      }
    }
  }
}`

**Comment by scsshomugenxv** [comment]
This is the enire message I get in the console: 

The "--using-cache" option does not exist.  
                                              
fix [--config CONFIG] [--config-file [CONFIG-FILE]] [--dry-run] [--level LEVEL] [--fixers FIXERS] [--diff] [--format FORMAT] [--] [<path>]

**Comment by scsshomugenxv** [comment]
Okay, I have it working now, looks like I somehow ended up installing an older verion of php-cs-fixer. Thanks for looking into this.

**Comment by Glavin001** [comment]
> an older verion of php-cs-fixer

I would like the Unibeautify PHP-CS-Fixer beautifier to automatically detect older versions of `php-cs-fixer` executable and use the appropriate CLI arguments.

Applicable code: https://github.com/Unibeautify/beautifier-php-cs-fixer/blob/master/src/index.ts#L109

Please feel free to create an issue over at https://github.com/Unibeautify/beautifier-php-cs-fixer/issues with details about the PHP-CS-Fixer versions used and the expected CLI arguments. Thanks!
