### ISSUE TITLE
Add Stylelint beautifier support to Unibeautify for VSCode

### ISSUE THREAD

**Issue by demartini** [Unibeautify/vscode#174]
Hello guys,

I would like to know how do I configure stylelint in Unibeautify?

I could not find any explanation in the documentation.

Thanks.

**Comment by Glavin001** [comment]
Stylelint is not yet supported in Unibeautify VSCode: https://github.com/Unibeautify/vscode/blob/master/src/beautifiers.ts

Pull Requests -- similar to https://github.com/Unibeautify/vscode/pull/137 -- are welcome to add support.

Beautifier Stylelint: https://github.com/Unibeautify/beautifier-stylelint/

@stevenzeck @muuvmuuv may be able to answer questions as well.

**Comment by Glavin001** [comment]
@stevenzeck @muuvmuuv what's the status of https://github.com/Unibeautify/beautifier-stylelint/ ? Is it in working order and could be added to VSCode and the website?

**Comment by stevenzeck** [comment]
I haven't touched it for a while. I can update everything and publish it for use in editors and the website

**Comment by Glavin001** [comment]
Thank you, @stevenzeck !

**Comment by Glavin001** [comment]
✅ Added to website: https://github.com/Unibeautify/website/pull/261
See https://unibeautify.com/docs/beautifier-stylelint

Working on adding to VSCode extension now.

**Comment by Glavin001** [comment]
✅ Added Stylelint: https://github.com/Unibeautify/vscode/pull/260
