### ISSUE TITLE
How do I paste the helper config code?

### ISSUE THREAD

**Issue by ognik777** [Unibeautify/vscode#206]
Sorry for my ignorance, I only recently started using vs code.
I ran the config helper and clicked 'copy' - but what do I do with it please?  I'm guessing it should be pasted into a file - but which/where is it?
Thanks

**Comment by Glavin001** [comment]
I recommend reading:
- https://github.com/Unibeautify/vscode#pencil-example-configuration-file
- https://unibeautify.com/docs/config-file.html

Let me know if you still have questions and we can reopen. 😃

**Comment by Glavin001** [comment]
If you're familiar with React it would be great if you could contribute to https://github.com/Unibeautify/assistant/blob/master/src/pages/setup/export-config.tsx and improve the configuration helper tool. I agree, this is not entirely clear:

![image](https://user-images.githubusercontent.com/1885333/80285413-1e362680-86fb-11ea-8be1-e56346bf24fc.png)


Thanks!

**Comment by Glavin001** [comment]
Improving assistant instructions in https://github.com/Unibeautify/assistant/pull/185
