### ISSUE TITLE
No formatter found for PHP files

### ISSUE THREAD

**Issue by odahcam** [Unibeautify/vscode#21]
I installed the extension.
Reloaded `vscode`.
When I tryied to format, `vscode` said:
> There is no formatter for 'php'-files installed.

![image](https://user-images.githubusercontent.com/3942006/38768647-7c169fcc-3fcd-11e8-9b1c-ec284e936f9d.png)

**Comment by Glavin001** [comment]
> There is no formatter for 'php'-files installed.

PHP is not yet supported.

See the website for support: https://unibeautify.com/

Also `Unibeautify.beautifyFile` has been removed. Use the builtin formatting for VSCode: https://stackoverflow.com/a/29973358/2578205

@szeck87 
 we should remove https://github.com/Unibeautify/vscode/blob/a684272ac1eb92e748f2dd9b3e2ef2d81d7e9649/package.json#L52-L63 . Pull Requests welcome, @odahcam !

**Comment by odahcam** [comment]
Let's do so. 

What is missing for PHP support?

> I used to use atom-beautify and it's idea of integrating things is something vscode really needs. Glad you came for vscode too.

**Comment by Glavin001** [comment]
> What is missing for PHP support?

Adding a new beautifier like https://github.com/Unibeautify/beautifier-php-cs-fixer to https://github.com/Unibeautify/vscode/blob/master/src/beautifiers.ts

The big issue is the `beautifier-php-cs-fixer` above needs work. It is not configurable right now. Also, maybe PHP developers do not want to use PHP-CS-Fixer and instead use another, which is not yet supported.

**Comment by szeck87** [comment]
Prettier will also have it's own PHP formatter, https://github.com/prettier/plugin-php

**Comment by odahcam** [comment]
I tryied to use Prettier, but I had to get back to the CLI php-cs-fixer, cause I couldn't get Prettier properly configured. :/

Also, it seems like Unibeautify is not "consuming" my `.eslintrc` file, neighter my `tslint.json`. I'm a little confused here, but if I'd use it for PHP with php-cs-fixer installed it should use my `.php_cs` configurations, right?

About the fixer, I'm studing it and I will try to help ASAP.

**Comment by szeck87** [comment]
Prettier errors out completely if you have the plugin in the `format` function but don't have it installed.  So yea, either need to check to see if the plugin is installed or include the install in the beautifier-prettier package.

The plugin is installed as a regular node module, so no need to specify where the plugin is.  And there isn't any configuration available as of right now, so no need to add options.

**Comment by odahcam** [comment]
But, if I have any configuration dotfile for some lang, e.g. `.eslintrc`, that config should affect my results, right?

**Comment by szeck87** [comment]
It really depends on what the beautifier supports.  Prettier has limited options for you to configure as it's an opinionated formatter.

I don't it works in VSCode yet as there are a couple of issues.

**Comment by Glavin001** [comment]
Configuration files such as `.eslintrc` and `.prettierrc` do not, yet, work. It is next on my priority list 😃 .

**Comment by odahcam** [comment]
That's a little sad, beautifiers should use their respective configurations, once they would be just executed by Unibeautify, the beautifier layer should not change the natural behavior of the original beautifier (consuming a own config file, in this case). Where should I start a proper discussion about that?

**Comment by szeck87** [comment]
There is already an open issue, https://github.com/Unibeautify/unibeautify/issues/48.  As @Glavin001 said it's next on the roadmap.

**Comment by Glavin001** [comment]
> Where should I start a proper discussion about that?

https://github.com/Unibeautify/unibeautify/issues/48

> That's a little sad, beautifiers should use their respective configurations, once they would be just executed by Unibeautify, the beautifier layer should not change the natural behavior of the original beautifier (consuming a own config file, in this case).

It's not sad, it's a feature 😉 .

An objective of Unibeautify is to abstract and unify configuration. If you have HTML, CSS, JavaScript, and PHP in your project then this could mean you have any of the following:
- HTML
    - `.jsbeautifyrc` from https://github.com/beautify-web/js-beautify#loading-settings-from-environment-or-jsbeautifyrc-javascript-only
- CSS
  - `.prettierrc` from https://prettier.io/docs/en/configuration.html
  - `.jsbeautifyrc` from https://github.com/beautify-web/js-beautify#loading-settings-from-environment-or-jsbeautifyrc-javascript-only
- JavaScript
  - `.eslintrc` from https://eslint.org/docs/user-guide/configuring
  - `.prettierrc` from https://prettier.io/docs/en/configuration.html
  - `.jsbeautifyrc` from https://github.com/beautify-web/js-beautify#loading-settings-from-environment-or-jsbeautifyrc-javascript-only
- PHP
  - `.php_cs.dist` from https://github.com/FriendsOfPHP/PHP-CS-Fixer#config-file

And each of these beautifiers may have different option names for the same option. For example, Prettier calls it `tabWidth` while JS-Beautify calls it `indent_size`.

With Unibeautify your configuration file could be:
- `.unibeautifyrc.yml` for HTML, CSS, JavaScript, PHP

And Unibeautify options are the same regardless of beautifier. See https://unibeautify.com/docs/option-indent-size.html 

My objective for Unibeautify is to provide a better experience for beautifiers -- through automatically generated documentation, editor integration, etc -- than even their own maintainers provide.

**Comment by odahcam** [comment]
Nice and thanks @Glavin001 and @szeck87, I will continue there and let this issue open for the initial issue.

**Comment by szeck87** [comment]
This should be resolved now with the 0.4.0 release.
