### ISSUE TITLE
Add Beautifiers support table to README

### ISSUE THREAD

**Issue by odahcam** [Unibeautify/vscode#23]
#### This is a:

feature request

#### Expected beahvior:

Like atom-beautify's one:

![image](https://user-images.githubusercontent.com/3942006/38780657-8af3bf28-40b0-11e8-8d6a-fb1bf745c015.png)

#### Anything else we should know?

This is very, VERY useful. The website doesn't make that point clear and for developers support tables are the final word about "if that works or not".

**Comment by szeck87** [comment]
@odahcam this is what http://unibeautify.com is meant to do. We could bullet list supported languages in the readme, but we're trying to avoid very long readme files like what atom-beautify has right now.

**Comment by Glavin001** [comment]
@odahcam : Thanks for this issue! The goal is the editor extensions (e.g. VSCode, Atom, etc) will be in sync with the documentation found at https://unibeautify.com . Each extension should provide the same user experience and feature set (eventually).

![image](https://user-images.githubusercontent.com/1885333/38784187-bd80cce0-40e4-11e8-8d6f-4eb9326d41d5.png)

I would prefer to keep the READMEs clean and focus on leveraging the [website's automatic generation](https://github.com/unibeautify/unibeautify) (similar to Atom-Beautify's auto-generated README).

What about adding an icon for the editors indicating the beautifier is supported? See https://unibeautify.com/docs/beautifier-eslint.html for example of a beautifier's page.
We could add a section called "Editor Support" and show the VSCode logo:
![image](https://user-images.githubusercontent.com/1885333/38784245-89f1d404-40e5-11e8-8a44-6d3c73e18672.png)
The logo would link back to https://github.com/Unibeautify/vscode

Thoughts? Pull Requests and feedback are very welcome! Thank you!

**Comment by odahcam** [comment]
That's a nice feature.

I still think that's important to show somewhere what each editor supports. That's good to know. 🙂

**Comment by Glavin001** [comment]
@odahcam How's this?

![image](https://user-images.githubusercontent.com/1885333/41640124-fea0996e-7436-11e8-967e-385419ecca24.png)

See https://github.com/Unibeautify/vscode/pull/52

**Comment by odahcam** [comment]
This is great @Glavin001 !
