### ISSUE TITLE
Configuration options?

### ISSUE THREAD

**Issue by JamesCoyle** [Unibeautify/vscode#41]
I don't know if I'm missing something obvious but I can't see a way to configure how each language is formatted. Is this something that is planned? I can't really use the extension as it is currently as formatting for tabs and newlines have been overridden from those defined in the VSCode options.

**Comment by Glavin001** [comment]
Hey @JamesCoyle ! Sorry about that. I implemented configuration support in #10 however I forgot to update the README.

I just added a new section: https://github.com/Unibeautify/vscode/#configure
The most up-to-date documentation can be found at https://unibeautify.com/ 
However, we are still working out how best to help new users.

Please let me know if you have any questions or suggestions! Thank you!

**Comment by Glavin001** [comment]
We can reopen this issue if the new documentation is insufficient 👍 .
