### ISSUE TITLE
Add auto fix on save or on type support

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/vscode#54]
I really love your stuff! Loved it before in atom and now in vscode, but I really need the auto-fix option from atom back. It was really comforting!

And it would be nice to specify the auto-fix option for each language individually.

**Comment by Glavin001** [comment]
Format on save is built-in to VSCode itself. See https://stackoverflow.com/a/39973431 

```
"editor.formatOnSave": true
```

And apparently they also support `editor.formtOnType` as well, although I have not tested this: https://github.com/Microsoft/vscode/issues/2044

```
editor.formatOnType: true
```

**Comment by Glavin001** [comment]
We can reopen if you have more questions 😃 .
