### ISSUE TITLE
Discussion: Rename repo

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/vscode#58]
Would it not be better to rename this repo to something like `vscode-plugin-unibeautify` just for readability and to create equality?

I‘m a really packaging victim (do you say that?) and it looks very confusing for me to have vscode forked when it actually is Unibeautify vscode.

**Comment by Glavin001** [comment]
I see your point. You're suggesting the following change?

```diff
- https://github.com/Unibeautify/vscode
+ https://github.com/Unibeautify/vscode-plugin-unibeautify
```

I am not a fan, as the `unibeautify` in the repo name would be redundant when in the context of the organization.

The organization is important. What I do personally, is have a folder for all `Unibeautify` repositories. This helps in the case you're discussing where you now know it is VSCode and *related to Unibeautify*. It also helps organizing repos when you have lots of repos cloned, as I do -- likely in the hundreds.

@szeck87 what are your thoughts?

**Comment by szeck87** [comment]
You can rename a repo via Settings and it will still maintain the fork.

![screen shot 2018-06-23 at 9 41 20 am](https://user-images.githubusercontent.com/8315038/41810790-9e2fae54-76c9-11e8-81c7-ffe81f1b3c8d.png)

**Comment by Glavin001** [comment]
I think this is something we won't be doing since it is unnecessary and plenty of workarounds to improve personal organization of cloned repositories 😄 . Thanks for creating the issue though!

**Comment by muuvmuuv** [comment]
Ohh thanks, did not know that is possible. Still learning 🙈

**Comment by Glavin001** [comment]
@muuvmuuv No problem! Let us know if you have any more questions 😃
