### ISSUE TITLE
I can't get ColdFusion to work.

### ISSUE THREAD

**Issue by slulego** [Unibeautify/vscode#94]
I installed the extension.
Created a `.unibeautifyrc.json` file inside the opened folder:

> {
>    "ColdFusion": {
>    "beautifiers": ["Pretty Diff"]
> }

VSCode 1.25.1
Windows 7

The only thing is I think the formatting works other files like html and json unless those are just built into Code.

**Comment by szeck87** [comment]
Two issues here:

1. vscodeLanguages for ColdFusion is missing from [unibeautify](https://github.com/Unibeautify/unibeautify/blob/master/src/languages.json#L1322). We should add `cfml` to it.

2. When the VSCode extension retrieves the extension and sends it to the `unibeautify.beautify` method, it sends it without the period (example:  `cfml` vs `.cfml`), so it doesn't find it.  That's a bug.
